TODO: Add Badge Chain Component
EzeLamar/sports-booking pull request #11
Opened 2024-02-14 22:57 UTC by EzeLamar

2024-02-14 22:58 UTC, EzeLamar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create badge chain for available timeslots](https://trello.com/c/Gv7x0yFE/32-create-badge-chain-for-available-timeslots)

2024-02-17 21:54 UTC, lubualo commented on app/components/UI/Badge.tsx
> +export default function Badge({ className = 'btn-primary', children, handleClick = () => {} }: Props) {
Are calling it Badge in the end? Wasn't it going to be BadgePill?

2024-02-17 21:56 UTC, lubualo requested changes

2024-02-17 21:56 UTC, lubualo commented on app/components/UI/Badge.tsx
> +export default function Badge({ className = 'btn-primary', children, handleClick = () => {} }: Props) {
Are we calling it Badge in the end? Wasn't it going to be BadgePill?

2024-02-18 21:48 UTC, lubualo approved these changes

2024-02-19 01:15 UTC, merged