SB-33: Added react-day-picker library
EzeLamar/sports-booking pull request #12
Opened 2024-02-17 21:47 UTC by lubualo

- Install the react-date-picker component library in project.

2024-02-17 21:47 UTC, lubualo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create datepicker component for available timeslots](https://trello.com/c/VwMb91FK/33-create-datepicker-component-for-available-timeslots)

2024-02-23 01:35 UTC, EzeLamar commented
Please attach a screenshot to the PR with the current style of the new component

2024-02-23 06:05 UTC, EzeLamar requested changes
Great Job! Left some observations and improvements.

2024-02-23 06:05 UTC, EzeLamar commented on app/components/UI/DatePicker.tsx
> +  if (!showPastDays) {
I think this logic is not necessary anymore. When you  include the prop `showPastDays=false` you are including in `DatePicker` the prop  `fromMonth={initialShownDate}` and initialShownDate depends on `showPastDays`

2024-02-23 18:32 UTC, lubualo commented on app/components/UI/DatePicker.tsx
> +  if (!showPastDays) {
I'm not sure that I understand this comment. The idea is that the `daysToDisable `prop is for specific dates that you want to disable (i.e. Christmas day or Workers day), which are not necessary in the past. Then:
- `showPastDays === true`: Then you have to only disable the dates received via prop.
- `showPastDays === false`: Then you have to disable the dates received via prop and the all the past days.

With regards to the initialShowDate:
- `showPastDays === true`: Then you show past months, as many as received via prop with `monthsBackToBeShown`.
- `showPastDays === false`: Then you don't show the past months, but you still have to disable the past days from this month (this was explained above).

2024-02-23 18:34 UTC, lubualo commented on app/components/UI/DatePicker.tsx
> +  const [month, setMonth] = useState<Date>(today);
Nice one!

2024-02-24 17:37 UTC, EzeLamar approved these changes
Remove the previous comment and add a new one

2024-02-24 17:37 UTC, EzeLamar commented on app/components/UI/DatePicker/DatePicker.tsx
> +  const disabledDays = [...daysToDisable];
Please add the next type to `disableDays ` to avoid warnings from TypeScript:
```suggestion
  const disabledDays : Matcher[] = [...daysToDisable];
```
The origin of this change is because the `disabled` prop from DayPicker expects to receive something of Type `Matcher[]`. Matcher could be a Date or a `DateRange` ({from: ... to: ...}) As you assign a DateRange to disabledDays [here](https://github.com/EzeLamar/sports-booking/pull/12/files#diff-20c40455d2fbc8cf970912a92db536e66d5648300bb9e2135f394483779276e5R33-R38) we need to explicitly indicate the type.

2024-02-24 17:38 UTC, EzeLamar commented on app/components/UI/DatePicker.tsx
> +  if (!showPastDays) {
I recheck the code and it is not necessary to remove it

2024-02-24 17:44 UTC, EzeLamar commented on app/components/UI/DatePicker/DatePicker.stories.tsx
> +      const [selectedDate, setSelectedDate] = useState<string[]>(today);
Please replace the type of the state from string[] to `Date`

2024-02-24 17:44 UTC, EzeLamar commented on app/components/UI/DatePicker/DatePicker.stories.tsx
> +export const HidePastDays: Story = {
What do you think to include the next story?
```
export const DisablePastDaysAndDayAfterTomorrow: Story = {
  args: {
    hidePastDays: true,
    daysToDisable: [dayAfterTomorrow],
  },
};
```

2024-02-24 23:01 UTC, merged