Task/sb 55 add google authentication
EzeLamar/sports-booking pull request #27
Opened 2024-04-17 00:17 UTC by EzeLamar

![image](https://github.com/EzeLamar/sports-booking/assets/26080561/5a31453f-f4d6-41e2-9449-b564b6032561)

2024-04-17 22:18 UTC, lubualo requested changes

2024-04-17 22:18 UTC, lubualo commented on app/components/Login/Signin/Signin.stories.tsx
> +	alert('google popup');
Can't you make it one line? So you don't need the rule exception?

2024-04-17 22:18 UTC, lubualo commented on app/components/Login/Signin/Signin.tsx
> -				title={LABELS.TITLE}
I think you can delete the TITLE property from LABELS now.

2024-04-17 22:18 UTC, lubualo commented on app/components/UI/Form/Form.tsx
> +	title?: string | null;
If the prop has the `?`, is it necessary to also write down the `| null`?

2024-04-17 22:18 UTC, lubualo commented on app/firebase/auth/signin.ts
> +export async function signIn(email: string, password: string) {
I think this is missing the return type.

2024-04-17 22:18 UTC, lubualo commented on app/firebase/auth/signin.ts
> +export async function googlePopUpSignIn() {
I think this is missing the `void` return type.

2024-04-17 22:18 UTC, lubualo commented on app/signin/page.tsx
> +	const handleGoogleLogin = () => {
I think this is missing the return type.

2024-04-17 22:18 UTC, lubualo commented on app/signin/page.tsx
> +		const signinGoogleUser = async () => {
I think this is missing the return type.

2024-04-18 14:24 UTC, EzeLamar commented on app/components/Login/Signin/Signin.stories.tsx
> +	alert('google popup');
No, the rule exception is to allow the use of an `alert` in the line 27 (next one to 26). Eslint does not allow us to use alerts and console.logs in the final code.

2024-04-18 14:29 UTC, EzeLamar commented on app/components/UI/Form/Form.tsx
> +	title?: string | null;
Yes, because in case it is not included as a prop the default value will be null

2024-04-18 15:01 UTC, EzeLamar commented on app/components/Login/Signin/Signin.tsx
> -				title={LABELS.TITLE}
Good catch, but need to continue showing the title on the legend of the Card:
https://github.com/EzeLamar/sports-booking/pull/27/files#diff-04bd939deaac59b25c4d1c44f0bd4bce0de6e257eafc3e448ed1b33cbbf4ccbeR37

2024-04-18 15:03 UTC, EzeLamar commented on app/firebase/auth/signin.ts
> +export async function googlePopUpSignIn() {
I updated the return of the firebase/auth:
* signin()
* signout()
* googlePopUpSignIn()

2024-04-19 18:07 UTC, lubualo approved these changes
Awesome!

2024-04-19 19:52 UTC, merged