SB-74: Add Reservation on FiresStore by Calendar
EzeLamar/sports-booking pull request #45
Opened 2024-06-05 01:27 UTC by EzeLamar

TODO

2024-06-05 01:28 UTC, EzeLamar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add reservations on firebase with Reservations Calendar](https://trello.com/c/3b6xf5Ct/74-add-reservations-on-firebase-with-reservations-calendar)

2024-06-05 23:09 UTC, EzeLamar commented on app/components/UI/Calendar/Calendar.tsx
> +			}
This block was reserved to use the edit reservation service in a future PR.

2024-06-08 15:32 UTC, lubualo requested changes

2024-06-08 15:32 UTC, lubualo commented on app/components/Reservations/Reservation.tsx
> +export type NewReservationType = {
I suggest that a reservation that has not been created yet could be called `reservationDraft`. Reservation draft won't have an ID as it hasn't been persisted in the DB yet, opposed to the normal reservation which exists in the DB

2024-06-10 03:14 UTC, EzeLamar commented on app/components/Reservations/Reservation.tsx
> +export type NewReservationType = {
Good catch! Fixed!

2024-06-12 21:39 UTC, lubualo commented on app/components/Reservations/Reservation.tsx
> +export type NewReservationType = {
Awesome

2024-06-12 21:39 UTC, lubualo approved these changes
Good job!

2024-06-13 16:09 UTC, merged