SB-66: Add price field in Reservation Form and Calendar
EzeLamar/sports-booking pull request #51
Opened 2024-06-14 06:20 UTC by EzeLamar

TODO PART-2

![image](https://github.com/EzeLamar/sports-booking/assets/26080561/540e3700-e38d-4638-a7e8-81a4973db35f)

2024-06-14 07:03 UTC, EzeLamar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add missing fields on  Reservation Form](https://trello.com/c/QBmPHuMl/66-add-missing-fields-on-reservation-form)

2024-06-14 19:49 UTC, lubualo requested changes
My only doubt is about the data type for 'price' as statd in other comments. This applies to Firestore DB data types as well.

2024-06-14 19:49 UTC, lubualo commented on app/(admin)/createReservation/page.tsx
> +				price: '1234',
Shouldn't price be a number instead of a string?

2024-06-14 19:49 UTC, lubualo commented on app/components/Reservations/ReservationForm.tsx
> +	price: string;
Doesn't it have to be a number instead of a string?

2024-06-14 19:49 UTC, lubualo commented on app/components/Reservations/ReservationForm.tsx
> +	price: string;
Maybe number instead of string?

2024-06-15 23:02 UTC, EzeLamar commented on app/(admin)/createReservation/page.tsx
> +				price: '1234',
Totally agree with you, I will replace it with `number`

2024-06-16 20:25 UTC, lubualo approved these changes
I like the fact that a _null_ price means there is no price set, as opposed to a price of 0 which would mean an intentional free cost.

2024-06-18 04:21 UTC, merged