SB-66: Add status field on Reservations Form and Calendar
EzeLamar/sports-booking pull request #52
Opened 2024-06-14 06:56 UTC by EzeLamar

Part 3/3

Changes:
* Add status field on Reservation Form.
* Update CRUD reservation adding the status field.
* Update Calendar
  * Add red border style for events with status booked (not paid).
  * Add grey color style for events with status canceled.

![image](https://github.com/EzeLamar/sports-booking/assets/26080561/7d24e678-38f6-4001-9d86-cdbf26360749)

![image](https://github.com/EzeLamar/sports-booking/assets/26080561/89bca1d1-a2be-497b-9d64-ac15b69898f8)

2024-06-14 07:03 UTC, EzeLamar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add missing fields on  Reservation Form](https://trello.com/c/QBmPHuMl/66-add-missing-fields-on-reservation-form)

2024-06-14 19:53 UTC, lubualo requested changes

2024-06-15 21:54 UTC, EzeLamar commented on app/components/Reservations/ReservationForm.tsx
> +
After a meeting, we decided not to use reference constants allocated to the database. Instead, we will restrict by firebase rules which are the valid values we can save. Also, in this PR I will define the key values ('booked', 'paid', 'canceled' ) as constants in a `module.ts` file.

2024-06-16 20:28 UTC, lubualo approved these changes
Way to go my friend!

2024-06-16 20:28 UTC, lubualo commented on app/components/Reservations/ReservationForm.tsx
> +	{
Great wording in my opinion here!

2024-06-18 04:25 UTC, merged