SB-81: Allow create multiple reservation ocurrences
EzeLamar/sports-booking pull request #54
Opened 2024-06-18 07:00 UTC by EzeLamar

TODO

2024-06-18 07:00 UTC, EzeLamar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Allow create multiple reservation occurrences](https://trello.com/c/tQg7oQCY/81-allow-create-multiple-reservation-occurrences)

2024-06-20 17:48 UTC, lubualo requested changes
I found a bug. If you start creating a Turno Fijo, complete all the fields but then turn off the Turno Fijo switch; it will create all the occurrencies anyeway (even though you just disabled it).

2024-06-24 19:34 UTC, EzeLamar commented
> I found a bug. If you start creating a Turno Fijo, complete all the fields but then turn off the Turno Fijo switch; it will create all the occurrencies anyeway (even though you just disabled it).

Fixed the bug. If the occurrences field was changed but we disabled the toggle button, then the handleSubmit will send only 1 occurrence by default.

2024-07-17 17:01 UTC, lubualo approved these changes
Way to go!

2024-07-17 19:54 UTC, merged